#!/bin/bash

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

(( $UID != 0 )) && echo 'Must be run as root' >&2 && exit 1

[[ -t 1 ]] && set -x

cd /var/empty

for rep in {extra,testing,staging,seblu}-{i686,x86_64} multilib{,-seblu,-testing,-staging}; do
	type -p $rep-build >/dev/null && $rep-build -c &>/dev/null
done

exit 0

# vim:set ts=2 sw=2 ft=sh noet:
